name: CI/CD Pipeline for Multiple Dockerfiles

on:
  push:
    branches:
      - release  
  pull_request:
    branches:
      - release  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - backend  
          - website  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

       
      - name: Install dependencies
        run: npm install
       
      - name: Build ${{ matrix.project }}
        run: npx nx build ${{matrix.project}}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

       
      - name: Build and push Docker image for ${{ matrix.project }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/${{ matrix.project }}/Dockerfile   
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.project }}:latest
